import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import ProjectSelectionPage from './pages/ProjectSelectionPage';
import ShoppingListPage from './pages/ShoppingListPage';
import LoginPage from './pages/LoginPage';
import { getToken, logout } from './services/api';
import './App.css';

const disclaimerParagraphs = [
  'The information provided by this DIY Project Planner is for general informational and educational purposes only and is not professional advice. The application may use artificial intelligence and other automated systems, which can make mistakes, omit important details, or produce outputs that are incomplete, outdated, or incorrect for your specific situation.',
  'Home renovation, plumbing, electrical, and related work can be dangerous and may be subject to local building codes, permitting requirements, and safety regulations that are not fully captured here. Before starting any project or purchasing materials, you are solely responsible for verifying all plans, measurements, materials, and methods, and for complying with applicable laws and codes.',
  'You should consult with a licensed contractor, plumber, electrician, engineer, inspector, or other qualified professional before relying on or acting upon any information generated by this tool. Use of this application is at your own risk, and the creator(s) of this tool disclaim any liability for injury, damage, code violations, or other losses arising from its use.',
];

function App() {
  return (
    <Router>
      <div className="app">
        <header className="app-header">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <h1>🏠 DIY Project Planner</h1>
              <p>Organize your home improvement projects</p>
            </div>
            <div>
              {getToken() ? (
                <button onClick={() => { logout(); window.location.href = '/'; }}>
                  Logout
                </button>
              ) : (
                <a href="/login">Login</a>
              )}
            </div>
          </div>
        </header>
        <main className="app-main">
          <Routes>
            <Route path="/login" element={<LoginPage />} />
            <Route path="/" element={<ProjectSelectionPage />} />
            <Route path="/shopping-list/:id" element={<ShoppingListPage />} />
          </Routes>
        </main>
        <footer className="app-footer">
          <div className="app-footer__inner">
            <p className="app-footer__copyright">&copy; 2026 DIY Project Planner</p>
            <section className="app-footer__disclaimer" aria-labelledby="footer-disclaimer-title">
              <h2 id="footer-disclaimer-title">Disclaimer</h2>
              {disclaimerParagraphs.map((paragraph) => (
                <p key={paragraph}>{paragraph}</p>
              ))}
            </section>
          </div>
        </footer>
      </div>
    </Router>
  );
}

export default App;
