import React from 'react';
import { BrowserRouter as Router, Link, Routes, Route, useLocation } from 'react-router-dom';
import ProjectSelectionPage from './pages/ProjectSelectionPage';
import ShoppingListPage from './pages/ShoppingListPage';
import LoginPage from './pages/LoginPage';
import { getToken, logout } from './services/api';
import heroImage from './assets/My.Home.reno.png';
import './App.css';

const disclaimerParagraphs = [
  'The information provided by this DIY Project Planner is for general informational and educational purposes only and is not professional advice. The application may use artificial intelligence and other automated systems, which can make mistakes, omit important details, or produce outputs that are incomplete, outdated, or incorrect for your specific situation.',
  'Home renovation, plumbing, electrical, and related work can be dangerous and may be subject to local building codes, permitting requirements, and safety regulations that are not fully captured here. Before starting any project or purchasing materials, you are solely responsible for verifying all plans, measurements, materials, and methods, and for complying with applicable laws and codes.',
  'You should consult with a licensed contractor, plumber, electrician, engineer, inspector, or other qualified professional before relying on or acting upon any information generated by this tool. Use of this application is at your own risk, and the creator(s) of this tool disclaim any liability for injury, damage, code violations, or other losses arising from its use.',
];
const appName = "The DIY Planner";

function AppLayout() {
  const location = useLocation();
  const isHomePage = location.pathname === '/';
  const isShoppingListPage = location.pathname.startsWith('/shopping-list/');
  const isLoggedIn = Boolean(getToken());

  return (
    <div className={`app ${isHomePage ? 'app--home' : 'app--inner'}`}>
      {isHomePage ? (
        <header
          className="home-hero"
          style={{
            backgroundImage: `linear-gradient(92deg, rgba(249, 242, 234, 0.96) 0%, rgba(249, 242, 234, 0.84) 40%, rgba(249, 242, 234, 0.2) 66%, rgba(249, 242, 234, 0.12) 100%), url(${heroImage})`,
          }}
        >
          <div className="home-hero__topbar">
            <Link to="/" className="brand-mark" aria-label="My Home Reno home">
              <span className="brand-mark__icon">⌂</span>
              <span className="brand-mark__text">{appName}</span>
            </Link>

            {isLoggedIn ? (
              <button className="nav-action" onClick={() => { logout(); window.location.href = '/'; }}>
                Logout
              </button>
            ) : (
              <Link to="/login" className="nav-action nav-action--link">Login</Link>
            )}
          </div>

          <div className="home-hero__content">
            <h1>Your AI co-pilot for every home project</h1>
            <p>Plan renovations with confidence, from your first sketch to your final shopping run.</p>
          </div>
        </header>
      ) : (
        <header className="site-nav">
          <div className="site-nav__inner">
            <Link to="/" className="brand-mark" aria-label={`${appName} home`}>
              <span className="brand-mark__icon">⌂</span>
              <span className="brand-mark__text">{appName}</span>
            </Link>

            <div className="site-nav__actions">
              <Link to="/" className="site-nav__link">Projects</Link>
              {isLoggedIn ? (
                <button className="nav-action" onClick={() => { logout(); window.location.href = '/'; }}>
                  Logout
                </button>
              ) : (
                <Link to="/login" className="nav-action nav-action--link">Login</Link>
              )}
            </div>
          </div>
        </header>
      )}

      <main className={`app-main ${isHomePage ? 'app-main--home' : 'app-main--inner'} ${isShoppingListPage ? 'app-main--shopping-list' : ''}`}>
        <Routes>
          <Route path="/login" element={<LoginPage />} />
          <Route path="/" element={<ProjectSelectionPage />} />
          <Route path="/shopping-list/:id" element={<ShoppingListPage />} />
        </Routes>
      </main>
      <footer className="app-footer">
        <div className="app-footer__inner">
          <p className="app-footer__copyright">&copy; 2026 {appName}</p>
          <section className="app-footer__disclaimer" aria-labelledby="footer-disclaimer-title">
            <h2 id="footer-disclaimer-title">Disclaimer</h2>
            {disclaimerParagraphs.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
          </section>
        </div>
      </footer>
    </div>
  );
}

function App() {
  return (
    <Router>
      <AppLayout />
    </Router>
  );
}

export default App;
