# Generated by Django 6.0.2 on 2026-02-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='product_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='product_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
