# Generated by Django 6.0.2 on 2026-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_material_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='steps',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
