# Generated by Django 6.0.2 on 2026-03-09 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_project_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('serpapi', 'SerpAPI'), ('openai', 'OpenAI')], max_length=20)),
                ('call_count', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Call Log',
                'verbose_name_plural': 'API Call Logs',
                'ordering': ['-date', 'service'],
                'unique_together': {('user', 'service', 'date')},
            },
        ),
    ]
